import { Medication } from '../types'

export const MEDICATION_SOURCE_DISCLAIMER =
  'Medication reference list supplied by the clinic. Medication selection, dose, frequency, duration, route and instructions must be determined by the treating clinician.'

export const REFERENCE_MEDICATION_SOURCE = 'Clinic supplied reference list'

export const FREQUENCY_OPTIONS = [
  'Once daily',
  'Twice daily',
  'Three times daily',
  'Four times daily',
  'Every 6 hours',
  'Every 8 hours',
  'Every 12 hours',
  'At bedtime',
  'As directed',
  'Other',
] as const

export const ROUTE_OPTIONS = [
  'Oral',
  'Topical',
  'Mouthwash',
  'Other',
] as const

export const DURATION_OPTIONS = [
  'Single dose',
  'As directed',
  'Other',
] as const

export const MEDICATION_CATEGORIES = [
  'All Categories',
  'Antibiotic',
  'Antibiotic combination',
  'Analgesic / Antipyretic',
  'Analgesic combination',
  'Analgesic / Muscle relaxant combination',
  'Analgesic / Anti-inflammatory combination',
  'Gastrointestinal',
  'Oral antiseptic',
  'Oral/dental topical preparation',
  'Antiseptic',
  'Oral care',
] as const

export const INITIAL_MEDICATION_MASTER: Omit<Medication, 'createdAt' | 'updatedAt'>[] = [
  // --- 1. ANTIBIOTICS ---
  {
    id: 'med_01',
    name: 'Amoxicillin',
    genericName: 'Amoxicillin',
    strength: '250 mg',
    dosageForm: 'Tablet/Capsule',
    category: 'Antibiotic',
    combination: false,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_02',
    name: 'Amoxicillin',
    genericName: 'Amoxicillin',
    strength: '500 mg',
    dosageForm: 'Tablet/Capsule',
    category: 'Antibiotic',
    combination: false,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_03',
    name: 'Cefixime',
    genericName: 'Cefixime',
    strength: '200 mg',
    dosageForm: 'Tablet',
    category: 'Antibiotic',
    combination: false,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_04',
    name: 'Ofloxacin',
    genericName: 'Ofloxacin',
    strength: '200 mg',
    dosageForm: 'Tablet',
    category: 'Antibiotic',
    combination: false,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_05',
    name: 'Amoxicillin + Potassium Clavulanate',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    strength: '375 mg',
    dosageForm: 'Tablet',
    category: 'Antibiotic combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_06',
    name: 'Amoxicillin + Potassium Clavulanate',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    strength: '625 mg',
    dosageForm: 'Tablet',
    category: 'Antibiotic combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_07',
    name: 'Dispersible Amoxicillin + Potassium Clavulanate',
    genericName: 'Amoxicillin + Potassium Clavulanate',
    strength: '228.5 mg',
    dosageForm: 'Dispersible formulation',
    category: 'Antibiotic combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },

  // --- 2. ANALGESICS / PAIN MANAGEMENT ---
  {
    id: 'med_08',
    name: 'Paracetamol',
    genericName: 'Paracetamol',
    strength: '500 mg',
    dosageForm: 'Tablet',
    category: 'Analgesic / Antipyretic',
    combination: false,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_09',
    name: 'Paracetamol',
    genericName: 'Paracetamol',
    strength: '650 mg',
    dosageForm: 'Tablet',
    category: 'Analgesic / Antipyretic',
    combination: false,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_10',
    name: 'Aceclofenac + Paracetamol',
    genericName: 'Aceclofenac + Paracetamol',
    strength: '425 mg',
    dosageForm: 'Tablet',
    category: 'Analgesic combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_11',
    name: 'Tramadol Hydrochloride + Paracetamol',
    genericName: 'Tramadol Hydrochloride + Paracetamol',
    strength: '362.5 mg',
    dosageForm: 'Tablet',
    category: 'Analgesic combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_12',
    name: 'Ibuprofen + Paracetamol',
    genericName: 'Ibuprofen + Paracetamol',
    strength: '725 mg',
    dosageForm: 'Tablet',
    category: 'Analgesic combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_13',
    name: 'Ibuprofen + Paracetamol',
    genericName: 'Ibuprofen + Paracetamol',
    strength: '225 mg',
    dosageForm: 'Dispersible tablet',
    category: 'Analgesic combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_14',
    name: 'Diclofenac Sodium + Paracetamol',
    genericName: 'Diclofenac Sodium + Paracetamol',
    strength: '375 mg',
    dosageForm: 'Tablet',
    category: 'Analgesic combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_15',
    name: 'Aceclofenac + Paracetamol + Chlorzoxazone',
    genericName: 'Aceclofenac + Paracetamol + Chlorzoxazone',
    strength: '675 mg',
    dosageForm: 'Tablet',
    category: 'Analgesic / Muscle relaxant combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_16',
    name: 'Zerodol-SP',
    genericName: 'Aceclofenac + Serratiopeptidase + Paracetamol',
    brandName: 'Zerodol-SP',
    strength: 'Combination',
    dosageForm: 'Tablet',
    category: 'Analgesic / Anti-inflammatory combination',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
    notes: 'Reference brand: Zerodol-SP. Primary generic composition: Aceclofenac + Serratiopeptidase + Paracetamol.',
  },

  // --- 3. GASTROINTESTINAL ---
  {
    id: 'med_17',
    name: 'Rabeprazole + Domperidone',
    genericName: 'Rabeprazole + Domperidone',
    strength: '30 mg',
    dosageForm: 'Capsule/Tablet',
    category: 'Gastrointestinal',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },

  // --- 4. ANTISEPTICS / ORAL CARE ---
  {
    id: 'med_18',
    name: 'Chlorhexidine Mouthwash',
    genericName: 'Chlorhexidine Gluconate',
    strength: '0.2% w/v',
    dosageForm: 'Mouthwash',
    category: 'Oral antiseptic',
    combination: false,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_19',
    name: 'Chlorhexidine Gluconate + Metronidazole + Lignocaine Gel',
    genericName: 'Chlorhexidine Gluconate + Metronidazole + Lignocaine',
    strength: 'Topical formulation',
    dosageForm: 'Gel',
    category: 'Oral/dental topical preparation',
    combination: true,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
    notes: 'Reference note from clinic list: "2–3 times a day". This is a reference note only; doctor must independently specify patient frequency.',
  },
  {
    id: 'med_20',
    name: 'Povidone Iodine',
    genericName: 'Povidone Iodine',
    strength: '2% w/v',
    dosageForm: 'Liquid/Gargle',
    category: 'Antiseptic',
    combination: false,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
  {
    id: 'med_21',
    name: 'Non-Fluorinated Dental Paste',
    genericName: 'Non-Fluorinated Dental Paste',
    strength: 'Standard paste',
    dosageForm: 'Dental Paste',
    category: 'Oral care',
    combination: false,
    active: true,
    source: REFERENCE_MEDICATION_SOURCE,
  },
]
