import { TreatmentItem } from '../types'

export const TREATMENT_SOURCE_NOTE =
  'Prices shown are reference ranges from the Kurnool Dental Doctors Association chart and may vary based on clinical assessment and clinic policy. Please confirm the final treatment cost with the clinic/doctor.'

export const GENERAL_DISCLAIMER_NOTE =
  'For treatments other than mentioned above, please check with your doctor.'

export const REFERENCE_SOURCE =
  'Kurnool Dental Doctors Association reference chart'

export const INITIAL_TREATMENT_MASTER: Omit<TreatmentItem, 'createdAt' | 'updatedAt'>[] = [
  // 1. Consultation & Diagnostics
  {
    id: 'trt_01',
    treatmentName: 'Consultation',
    category: 'Consultation & Diagnostics',
    minPrice: 200,
    maxPrice: 300,
    priceDisplay: '₹200–₹300',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_02',
    treatmentName: 'Dental X-Ray',
    category: 'Consultation & Diagnostics',
    minPrice: 200,
    maxPrice: 300,
    priceDisplay: '₹200–₹300',
    active: true,
    source: REFERENCE_SOURCE,
  },

  // 2. Extraction
  {
    id: 'trt_03',
    treatmentName: 'Simple Extraction',
    category: 'Extraction',
    minPrice: 1000,
    maxPrice: 1500,
    priceDisplay: '₹1,000–₹1,500',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_04',
    treatmentName: 'Fracture of Tough Tooth While Extraction',
    category: 'Extraction',
    minPrice: 2000,
    maxPrice: 3000,
    priceDisplay: '₹2,000–₹3,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_05',
    treatmentName: 'Wisdom Tooth Extraction',
    category: 'Extraction',
    minPrice: 2000,
    maxPrice: 3000,
    priceDisplay: '₹2,000–₹3,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_06',
    treatmentName: 'Impacted Wisdom Tooth',
    category: 'Extraction',
    minPrice: 4000,
    maxPrice: 7000,
    priceDisplay: '₹4,000–₹7,000',
    active: true,
    source: REFERENCE_SOURCE,
  },

  // 3. Filling
  {
    id: 'trt_07',
    treatmentName: 'Permanent Filling — GIC Cement',
    category: 'Filling',
    minPrice: 900,
    maxPrice: 1500,
    priceDisplay: '₹900–₹1,500',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_08',
    treatmentName: 'Permanent Filling — Composite / Silver Cement',
    category: 'Filling',
    minPrice: 1500,
    maxPrice: 3000,
    priceDisplay: '₹1,500–₹3,000',
    active: true,
    source: REFERENCE_SOURCE,
  },

  // 4. Cleaning
  {
    id: 'trt_09',
    treatmentName: 'Scaling or Cleaning',
    category: 'Cleaning',
    minPrice: 1200,
    maxPrice: 3000,
    priceDisplay: '₹1,200–₹3,000',
    active: true,
    source: REFERENCE_SOURCE,
  },

  // 5. Root Canal / Restorative
  {
    id: 'trt_10',
    treatmentName: 'Root Canal Treatment',
    category: 'Root Canal / Restorative',
    minPrice: 4000,
    maxPrice: 6000,
    priceDisplay: '₹4,000–₹6,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_11',
    treatmentName: 'Post and Core',
    category: 'Root Canal / Restorative',
    minPrice: 3500,
    maxPrice: 5000,
    priceDisplay: '₹3,500–₹5,000',
    active: true,
    source: REFERENCE_SOURCE,
  },

  // 6. Crowns
  {
    id: 'trt_12',
    treatmentName: 'Zirconia Crown',
    category: 'Crowns',
    minPrice: 9000,
    maxPrice: 15000,
    priceDisplay: '₹9,000–₹15,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_13',
    treatmentName: 'Metal Ceramic Crown',
    category: 'Crowns',
    minPrice: 4000,
    maxPrice: 6000,
    priceDisplay: '₹4,000–₹6,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_14',
    treatmentName: 'DMLS Crown',
    category: 'Crowns',
    minPrice: 6000,
    maxPrice: 9000,
    priceDisplay: '₹6,000–₹9,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_15',
    treatmentName: 'Ceramic Facing Crown',
    category: 'Crowns',
    minPrice: 2500,
    maxPrice: 3500,
    priceDisplay: '₹2,500–₹3,500',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_16',
    treatmentName: 'Metal Crown',
    category: 'Crowns',
    minPrice: 2000,
    maxPrice: 3000,
    priceDisplay: '₹2,000–₹3,000',
    active: true,
    source: REFERENCE_SOURCE,
  },

  // 7. Dentures
  {
    id: 'trt_17',
    treatmentName: 'Removable Partial Denture (1 Tooth)',
    category: 'Dentures',
    minPrice: 1000,
    maxPrice: 1500,
    priceDisplay: '₹1,000–₹1,500',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_18',
    treatmentName: 'Complete Denture',
    category: 'Dentures',
    minPrice: 20000,
    maxPrice: 60000,
    priceDisplay: '₹20,000–₹60,000',
    active: true,
    source: REFERENCE_SOURCE,
  },

  // 8. Orthodontics
  {
    id: 'trt_19',
    treatmentName: 'Metal Braces',
    category: 'Orthodontics',
    minPrice: 40000,
    maxPrice: 60000,
    priceDisplay: '₹40,000–₹60,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_20',
    treatmentName: 'Ceramic Braces',
    category: 'Orthodontics',
    minPrice: 50000,
    maxPrice: 70000,
    priceDisplay: '₹50,000–₹70,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_21',
    treatmentName: 'Self-Ligating Ceramic / Metal Braces',
    category: 'Orthodontics',
    minPrice: 80000,
    maxPrice: 100000,
    priceDisplay: '₹80,000–₹1,00,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_22',
    treatmentName: 'Fixed Retainer',
    category: 'Orthodontics',
    minPrice: 6000,
    maxPrice: 8000,
    priceDisplay: '₹6,000–₹8,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_23',
    treatmentName: 'Removable Retainer',
    category: 'Orthodontics',
    minPrice: 4000,
    maxPrice: 6000,
    priceDisplay: '₹4,000–₹6,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_24',
    treatmentName: 'Aligners / Lingual Orthodontics',
    category: 'Orthodontics',
    minPrice: 150000,
    maxPrice: null,
    priceDisplay: '₹1,50,000+',
    active: true,
    source: REFERENCE_SOURCE,
  },

  // 9. Periodontal / Surgical
  {
    id: 'trt_25',
    treatmentName: 'Full Mouth Flap Surgery',
    category: 'Periodontal / Surgical',
    minPrice: 19000,
    maxPrice: 30000,
    priceDisplay: '₹19,000–₹30,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_26',
    treatmentName: 'Laser Flap Surgery',
    category: 'Periodontal / Surgical',
    minPrice: 35000,
    maxPrice: 50000,
    priceDisplay: '₹35,000–₹50,000',
    active: true,
    source: REFERENCE_SOURCE,
  },

  // 10. Implant / Other Procedures
  {
    id: 'trt_27',
    treatmentName: 'Single Implant',
    category: 'Implant / Other Procedures',
    minPrice: 25000,
    maxPrice: 50000,
    priceDisplay: '₹25,000–₹50,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_28',
    treatmentName: 'Apicectomy Per Tooth',
    category: 'Implant / Other Procedures',
    minPrice: 4000,
    maxPrice: 7000,
    priceDisplay: '₹4,000–₹7,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_29',
    treatmentName: 'Myofunctional Therapy',
    category: 'Implant / Other Procedures',
    minPrice: 15000,
    maxPrice: 30000,
    priceDisplay: '₹15,000–₹30,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_30',
    treatmentName: 'Pulp Therapy & Stainless Steel Crown',
    category: 'Implant / Other Procedures',
    minPrice: 6000,
    maxPrice: 8000,
    priceDisplay: '₹6,000–₹8,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_31',
    treatmentName: 'Space Maintainers',
    category: 'Implant / Other Procedures',
    minPrice: 3000,
    maxPrice: 5000,
    priceDisplay: '₹3,000–₹5,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
  {
    id: 'trt_32',
    treatmentName: 'Minor Surgeries',
    category: 'Implant / Other Procedures',
    minPrice: 5000,
    maxPrice: 9000,
    priceDisplay: '₹5,000–₹9,000',
    active: true,
    source: REFERENCE_SOURCE,
    notes:
      'Includes procedures such as Operculectomy, Frenectomy, Crown Lengthening, Mucogingival procedures.',
  },
  {
    id: 'trt_33',
    treatmentName: 'Direct Composite Veneers and Polishing',
    category: 'Implant / Other Procedures',
    minPrice: 3000,
    maxPrice: 4000,
    priceDisplay: '₹3,000–₹4,000',
    active: true,
    source: REFERENCE_SOURCE,
  },
]

export const TREATMENT_CATEGORIES: string[] = [
  'All Categories',
  'Consultation & Diagnostics',
  'Extraction',
  'Filling',
  'Cleaning',
  'Root Canal / Restorative',
  'Crowns',
  'Dentures',
  'Orthodontics',
  'Periodontal / Surgical',
  'Implant / Other Procedures',
]
